name = "Origin Realms Deluxe"
author = "Verday"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5280adde5c0ba80ff25e8ff966f3b8e760c93fab8c9e9b03d74e34f6c61071f8"

[versions]
minecraft = "1.19.2"
quilt = "0.18.10"
